# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kinetix/risk/attribution.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kinetix/risk/attribution.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ekinetix/risk/attribution.proto\x12\x0ckinetix.risk\"\x8b\x01\n\x0bSectorInput\x12\x14\n\x0csector_label\x18\x01 \x01(\t\x12\x18\n\x10portfolio_weight\x18\x02 \x01(\x01\x12\x18\n\x10\x62\x65nchmark_weight\x18\x03 \x01(\x01\x12\x18\n\x10portfolio_return\x18\x04 \x01(\x01\x12\x18\n\x10\x62\x65nchmark_return\x18\x05 \x01(\x01\"_\n\x11\x41ttributionPeriod\x12*\n\x07sectors\x18\x01 \x03(\x0b\x32\x19.kinetix.risk.SectorInput\x12\x1e\n\x16total_benchmark_return\x18\x02 \x01(\x01\"M\n\x19\x42rinsonAttributionRequest\x12\x30\n\x07periods\x18\x01 \x03(\x0b\x32\x1f.kinetix.risk.AttributionPeriod\"\x8b\x02\n\x17SectorAttributionResult\x12\x14\n\x0csector_label\x18\x01 \x01(\t\x12\x18\n\x10portfolio_weight\x18\x02 \x01(\x01\x12\x18\n\x10\x62\x65nchmark_weight\x18\x03 \x01(\x01\x12\x18\n\x10portfolio_return\x18\x04 \x01(\x01\x12\x18\n\x10\x62\x65nchmark_return\x18\x05 \x01(\x01\x12\x19\n\x11\x61llocation_effect\x18\x06 \x01(\x01\x12\x18\n\x10selection_effect\x18\x07 \x01(\x01\x12\x1a\n\x12interaction_effect\x18\x08 \x01(\x01\x12!\n\x19total_active_contribution\x18\t \x01(\x01\"\xd4\x01\n\x1a\x42rinsonAttributionResponse\x12\x36\n\x07sectors\x18\x01 \x03(\x0b\x32%.kinetix.risk.SectorAttributionResult\x12\x1b\n\x13total_active_return\x18\x02 \x01(\x01\x12\x1f\n\x17total_allocation_effect\x18\x03 \x01(\x01\x12\x1e\n\x16total_selection_effect\x18\x04 \x01(\x01\x12 \n\x18total_interaction_effect\x18\x05 \x01(\x01\x32\x86\x01\n\x12\x41ttributionService\x12p\n\x1b\x43\x61lculateBrinsonAttribution\x12\'.kinetix.risk.BrinsonAttributionRequest\x1a(.kinetix.risk.BrinsonAttributionResponseB\x1a\n\x16\x63om.kinetix.proto.riskP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kinetix.risk.attribution_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.kinetix.proto.riskP\001'
  _globals['_SECTORINPUT']._serialized_start=49
  _globals['_SECTORINPUT']._serialized_end=188
  _globals['_ATTRIBUTIONPERIOD']._serialized_start=190
  _globals['_ATTRIBUTIONPERIOD']._serialized_end=285
  _globals['_BRINSONATTRIBUTIONREQUEST']._serialized_start=287
  _globals['_BRINSONATTRIBUTIONREQUEST']._serialized_end=364
  _globals['_SECTORATTRIBUTIONRESULT']._serialized_start=367
  _globals['_SECTORATTRIBUTIONRESULT']._serialized_end=634
  _globals['_BRINSONATTRIBUTIONRESPONSE']._serialized_start=637
  _globals['_BRINSONATTRIBUTIONRESPONSE']._serialized_end=849
  _globals['_ATTRIBUTIONSERVICE']._serialized_start=852
  _globals['_ATTRIBUTIONSERVICE']._serialized_end=986
# @@protoc_insertion_point(module_scope)
