# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kinetix.risk import attribution_pb2 as kinetix_dot_risk_dot_attribution__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kinetix/risk/attribution_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AttributionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateBrinsonAttribution = channel.unary_unary(
                '/kinetix.risk.AttributionService/CalculateBrinsonAttribution',
                request_serializer=kinetix_dot_risk_dot_attribution__pb2.BrinsonAttributionRequest.SerializeToString,
                response_deserializer=kinetix_dot_risk_dot_attribution__pb2.BrinsonAttributionResponse.FromString,
                _registered_method=True)


class AttributionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateBrinsonAttribution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttributionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateBrinsonAttribution': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateBrinsonAttribution,
                    request_deserializer=kinetix_dot_risk_dot_attribution__pb2.BrinsonAttributionRequest.FromString,
                    response_serializer=kinetix_dot_risk_dot_attribution__pb2.BrinsonAttributionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kinetix.risk.AttributionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kinetix.risk.AttributionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AttributionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateBrinsonAttribution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kinetix.risk.AttributionService/CalculateBrinsonAttribution',
            kinetix_dot_risk_dot_attribution__pb2.BrinsonAttributionRequest.SerializeToString,
            kinetix_dot_risk_dot_attribution__pb2.BrinsonAttributionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
