# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kinetix.risk import risk_calculation_pb2 as kinetix_dot_risk_dot_risk__calculation__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kinetix/risk/risk_calculation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RiskCalculationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateVaR = channel.unary_unary(
                '/kinetix.risk.RiskCalculationService/CalculateVaR',
                request_serializer=kinetix_dot_risk_dot_risk__calculation__pb2.VaRRequest.SerializeToString,
                response_deserializer=kinetix_dot_risk_dot_risk__calculation__pb2.VaRResponse.FromString,
                _registered_method=True)
        self.CalculateVaRStream = channel.stream_stream(
                '/kinetix.risk.RiskCalculationService/CalculateVaRStream',
                request_serializer=kinetix_dot_risk_dot_risk__calculation__pb2.VaRRequest.SerializeToString,
                response_deserializer=kinetix_dot_risk_dot_risk__calculation__pb2.VaRResponse.FromString,
                _registered_method=True)
        self.Valuate = channel.unary_unary(
                '/kinetix.risk.RiskCalculationService/Valuate',
                request_serializer=kinetix_dot_risk_dot_risk__calculation__pb2.ValuationRequest.SerializeToString,
                response_deserializer=kinetix_dot_risk_dot_risk__calculation__pb2.ValuationResponse.FromString,
                _registered_method=True)


class RiskCalculationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateVaR(self, request, context):
        """Deprecated: use Valuate instead
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateVaRStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Valuate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RiskCalculationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateVaR': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateVaR,
                    request_deserializer=kinetix_dot_risk_dot_risk__calculation__pb2.VaRRequest.FromString,
                    response_serializer=kinetix_dot_risk_dot_risk__calculation__pb2.VaRResponse.SerializeToString,
            ),
            'CalculateVaRStream': grpc.stream_stream_rpc_method_handler(
                    servicer.CalculateVaRStream,
                    request_deserializer=kinetix_dot_risk_dot_risk__calculation__pb2.VaRRequest.FromString,
                    response_serializer=kinetix_dot_risk_dot_risk__calculation__pb2.VaRResponse.SerializeToString,
            ),
            'Valuate': grpc.unary_unary_rpc_method_handler(
                    servicer.Valuate,
                    request_deserializer=kinetix_dot_risk_dot_risk__calculation__pb2.ValuationRequest.FromString,
                    response_serializer=kinetix_dot_risk_dot_risk__calculation__pb2.ValuationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kinetix.risk.RiskCalculationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kinetix.risk.RiskCalculationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RiskCalculationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateVaR(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kinetix.risk.RiskCalculationService/CalculateVaR',
            kinetix_dot_risk_dot_risk__calculation__pb2.VaRRequest.SerializeToString,
            kinetix_dot_risk_dot_risk__calculation__pb2.VaRResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateVaRStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/kinetix.risk.RiskCalculationService/CalculateVaRStream',
            kinetix_dot_risk_dot_risk__calculation__pb2.VaRRequest.SerializeToString,
            kinetix_dot_risk_dot_risk__calculation__pb2.VaRResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Valuate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kinetix.risk.RiskCalculationService/Valuate',
            kinetix_dot_risk_dot_risk__calculation__pb2.ValuationRequest.SerializeToString,
            kinetix_dot_risk_dot_risk__calculation__pb2.ValuationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
