package com.kinetix.audit.seed

import com.kinetix.audit.model.AuditEvent
import com.kinetix.audit.persistence.AuditEventRepository
import org.slf4j.LoggerFactory
import java.time.Instant
import java.time.temporal.ChronoUnit

class DevDataSeeder(
    private val repository: AuditEventRepository,
) {
    private val log = LoggerFactory.getLogger(DevDataSeeder::class.java)

    suspend fun seed() {
        val existing = repository.findAll()
        if (existing.isNotEmpty()) {
            log.info("Audit events already present ({} events), skipping seed", existing.size)
            return
        }

        log.info("Seeding {} audit events", EVENTS.size)

        for (event in EVENTS) {
            repository.save(event)
        }

        log.info("Audit event seeding complete")
    }

    companion object {
        private val BASE_TIME = Instant.parse("2026-02-21T14:00:00Z")
        private fun day(n: Long): Instant = BASE_TIME.plus(n, ChronoUnit.DAYS)
        private fun receivedAfter(tradedAt: Instant): Instant = tradedAt.plusSeconds(1)

        private val RECEIVED_AT = receivedAfter(BASE_TIME)
        private const val TRADED_AT = "2026-02-21T14:00:00Z"

        private fun dayStr(n: Long): String = day(n).toString()
        private fun receivedAtDay(n: Long): Instant = receivedAfter(day(n))

        val EVENTS: List<AuditEvent> = listOf(
            // ── equity-growth portfolio: 5 equity trades (existing) ──
            AuditEvent(
                tradeId = "seed-eq-aapl-001",
                portfolioId = "equity-growth",
                instrumentId = "AAPL",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "150",
                priceAmount = "185.50",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
            ),
            AuditEvent(
                tradeId = "seed-eq-googl-001",
                portfolioId = "equity-growth",
                instrumentId = "GOOGL",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "80",
                priceAmount = "175.20",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
            ),
            AuditEvent(
                tradeId = "seed-eq-msft-001",
                portfolioId = "equity-growth",
                instrumentId = "MSFT",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "120",
                priceAmount = "420.00",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
            ),
            AuditEvent(
                tradeId = "seed-eq-amzn-001",
                portfolioId = "equity-growth",
                instrumentId = "AMZN",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "100",
                priceAmount = "205.75",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
            ),
            AuditEvent(
                tradeId = "seed-eq-tsla-001",
                portfolioId = "equity-growth",
                instrumentId = "TSLA",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "200",
                priceAmount = "248.30",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
            ),

            // ── multi-asset portfolio: 6 trades across asset classes (existing) ──
            AuditEvent(
                tradeId = "seed-ma-aapl-001",
                portfolioId = "multi-asset",
                instrumentId = "AAPL",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "50",
                priceAmount = "186.00",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
            ),
            AuditEvent(
                tradeId = "seed-ma-eurusd-001",
                portfolioId = "multi-asset",
                instrumentId = "EURUSD",
                assetClass = "FX",
                side = "BUY",
                quantity = "100000",
                priceAmount = "1.0842",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
            ),
            AuditEvent(
                tradeId = "seed-ma-us10y-001",
                portfolioId = "multi-asset",
                instrumentId = "US10Y",
                assetClass = "FIXED_INCOME",
                side = "BUY",
                quantity = "500",
                priceAmount = "96.75",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
            ),
            AuditEvent(
                tradeId = "seed-ma-gc-001",
                portfolioId = "multi-asset",
                instrumentId = "GC",
                assetClass = "COMMODITY",
                side = "BUY",
                quantity = "10",
                priceAmount = "2045.60",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
            ),
            AuditEvent(
                tradeId = "seed-ma-spx-put-001",
                portfolioId = "multi-asset",
                instrumentId = "SPX-PUT-4500",
                assetClass = "DERIVATIVE",
                side = "BUY",
                quantity = "25",
                priceAmount = "32.50",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
            ),
            AuditEvent(
                tradeId = "seed-ma-msft-001",
                portfolioId = "multi-asset",
                instrumentId = "MSFT",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "75",
                priceAmount = "418.50",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
            ),

            // ── fixed-income portfolio: 3 fixed income trades (existing) ──
            AuditEvent(
                tradeId = "seed-fi-us2y-001",
                portfolioId = "fixed-income",
                instrumentId = "US2Y",
                assetClass = "FIXED_INCOME",
                side = "BUY",
                quantity = "1000",
                priceAmount = "99.25",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
            ),
            AuditEvent(
                tradeId = "seed-fi-us10y-001",
                portfolioId = "fixed-income",
                instrumentId = "US10Y",
                assetClass = "FIXED_INCOME",
                side = "BUY",
                quantity = "800",
                priceAmount = "96.50",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
            ),
            AuditEvent(
                tradeId = "seed-fi-us30y-001",
                portfolioId = "fixed-income",
                instrumentId = "US30Y",
                assetClass = "FIXED_INCOME",
                side = "BUY",
                quantity = "500",
                priceAmount = "92.10",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
            ),

            // ── emerging-markets portfolio: 5 positions + 1 sell ──
            AuditEvent(
                tradeId = "seed-em-baba-001",
                portfolioId = "emerging-markets",
                instrumentId = "BABA",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "400",
                priceAmount = "83.20",
                priceCurrency = "USD",
                tradedAt = dayStr(1),
                receivedAt = receivedAtDay(1),
            ),
            AuditEvent(
                tradeId = "seed-em-tsla-001",
                portfolioId = "emerging-markets",
                instrumentId = "TSLA",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "60",
                priceAmount = "250.10",
                priceCurrency = "USD",
                tradedAt = dayStr(1),
                receivedAt = receivedAtDay(1),
            ),
            AuditEvent(
                tradeId = "seed-em-eurusd-001",
                portfolioId = "emerging-markets",
                instrumentId = "EURUSD",
                assetClass = "FX",
                side = "BUY",
                quantity = "75000",
                priceAmount = "1.0850",
                priceCurrency = "USD",
                tradedAt = dayStr(1),
                receivedAt = receivedAtDay(1),
            ),
            AuditEvent(
                tradeId = "seed-em-gbpusd-001",
                portfolioId = "emerging-markets",
                instrumentId = "GBPUSD",
                assetClass = "FX",
                side = "BUY",
                quantity = "50000",
                priceAmount = "1.2580",
                priceCurrency = "USD",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
            ),
            AuditEvent(
                tradeId = "seed-em-usdjpy-001",
                portfolioId = "emerging-markets",
                instrumentId = "USDJPY",
                assetClass = "FX",
                side = "BUY",
                quantity = "80000",
                priceAmount = "150.20",
                priceCurrency = "USD",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
            ),
            AuditEvent(
                tradeId = "seed-em-baba-002",
                portfolioId = "emerging-markets",
                instrumentId = "BABA",
                assetClass = "EQUITY",
                side = "SELL",
                quantity = "100",
                priceAmount = "86.50",
                priceCurrency = "USD",
                tradedAt = dayStr(4),
                receivedAt = receivedAtDay(4),
            ),

            // ── macro-hedge portfolio: 6 positions + 1 sell ──
            AuditEvent(
                tradeId = "seed-mh-usdjpy-001",
                portfolioId = "macro-hedge",
                instrumentId = "USDJPY",
                assetClass = "FX",
                side = "BUY",
                quantity = "120000",
                priceAmount = "149.80",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
            ),
            AuditEvent(
                tradeId = "seed-mh-gc-001",
                portfolioId = "macro-hedge",
                instrumentId = "GC",
                assetClass = "COMMODITY",
                side = "BUY",
                quantity = "15",
                priceAmount = "2040.00",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
            ),
            AuditEvent(
                tradeId = "seed-mh-cl-001",
                portfolioId = "macro-hedge",
                instrumentId = "CL",
                assetClass = "COMMODITY",
                side = "BUY",
                quantity = "50",
                priceAmount = "76.80",
                priceCurrency = "USD",
                tradedAt = dayStr(1),
                receivedAt = receivedAtDay(1),
            ),
            AuditEvent(
                tradeId = "seed-mh-si-001",
                portfolioId = "macro-hedge",
                instrumentId = "SI",
                assetClass = "COMMODITY",
                side = "BUY",
                quantity = "200",
                priceAmount = "23.10",
                priceCurrency = "USD",
                tradedAt = dayStr(1),
                receivedAt = receivedAtDay(1),
            ),
            AuditEvent(
                tradeId = "seed-mh-de10y-001",
                portfolioId = "macro-hedge",
                instrumentId = "DE10Y",
                assetClass = "FIXED_INCOME",
                side = "BUY",
                quantity = "300",
                priceAmount = "97.80",
                priceCurrency = "EUR",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
            ),
            AuditEvent(
                tradeId = "seed-mh-spx-put-001",
                portfolioId = "macro-hedge",
                instrumentId = "SPX-PUT-4500",
                assetClass = "DERIVATIVE",
                side = "BUY",
                quantity = "40",
                priceAmount = "31.20",
                priceCurrency = "USD",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
            ),
            AuditEvent(
                tradeId = "seed-mh-gc-002",
                portfolioId = "macro-hedge",
                instrumentId = "GC",
                assetClass = "COMMODITY",
                side = "SELL",
                quantity = "5",
                priceAmount = "2060.50",
                priceCurrency = "USD",
                tradedAt = dayStr(4),
                receivedAt = receivedAtDay(4),
            ),

            // ── tech-momentum portfolio: 4 positions + 1 sell ──
            AuditEvent(
                tradeId = "seed-tm-nvda-001",
                portfolioId = "tech-momentum",
                instrumentId = "NVDA",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "90",
                priceAmount = "885.00",
                priceCurrency = "USD",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
            ),
            AuditEvent(
                tradeId = "seed-tm-meta-001",
                portfolioId = "tech-momentum",
                instrumentId = "META",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "110",
                priceAmount = "502.30",
                priceCurrency = "USD",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
            ),
            AuditEvent(
                tradeId = "seed-tm-msft-001",
                portfolioId = "tech-momentum",
                instrumentId = "MSFT",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "85",
                priceAmount = "421.50",
                priceCurrency = "USD",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
            ),
            AuditEvent(
                tradeId = "seed-tm-googl-001",
                portfolioId = "tech-momentum",
                instrumentId = "GOOGL",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "100",
                priceAmount = "176.80",
                priceCurrency = "USD",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
            ),
            AuditEvent(
                tradeId = "seed-tm-meta-002",
                portfolioId = "tech-momentum",
                instrumentId = "META",
                assetClass = "EQUITY",
                side = "SELL",
                quantity = "30",
                priceAmount = "510.00",
                priceCurrency = "USD",
                tradedAt = dayStr(6),
                receivedAt = receivedAtDay(6),
            ),

            // ── balanced-income portfolio: 5 positions + 1 sell ──
            AuditEvent(
                tradeId = "seed-bi-us10y-001",
                portfolioId = "balanced-income",
                instrumentId = "US10Y",
                assetClass = "FIXED_INCOME",
                side = "BUY",
                quantity = "600",
                priceAmount = "96.60",
                priceCurrency = "USD",
                tradedAt = dayStr(1),
                receivedAt = receivedAtDay(1),
            ),
            AuditEvent(
                tradeId = "seed-bi-us30y-001",
                portfolioId = "balanced-income",
                instrumentId = "US30Y",
                assetClass = "FIXED_INCOME",
                side = "BUY",
                quantity = "400",
                priceAmount = "92.30",
                priceCurrency = "USD",
                tradedAt = dayStr(1),
                receivedAt = receivedAtDay(1),
            ),
            AuditEvent(
                tradeId = "seed-bi-de10y-001",
                portfolioId = "balanced-income",
                instrumentId = "DE10Y",
                assetClass = "FIXED_INCOME",
                side = "BUY",
                quantity = "250",
                priceAmount = "97.90",
                priceCurrency = "EUR",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
            ),
            AuditEvent(
                tradeId = "seed-bi-jpm-001",
                portfolioId = "balanced-income",
                instrumentId = "JPM",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "150",
                priceAmount = "208.40",
                priceCurrency = "USD",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
            ),
            AuditEvent(
                tradeId = "seed-bi-aapl-001",
                portfolioId = "balanced-income",
                instrumentId = "AAPL",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "70",
                priceAmount = "187.20",
                priceCurrency = "USD",
                tradedAt = dayStr(4),
                receivedAt = receivedAtDay(4),
            ),
            AuditEvent(
                tradeId = "seed-bi-us30y-002",
                portfolioId = "balanced-income",
                instrumentId = "US30Y",
                assetClass = "FIXED_INCOME",
                side = "SELL",
                quantity = "100",
                priceAmount = "93.10",
                priceCurrency = "USD",
                tradedAt = dayStr(6),
                receivedAt = receivedAtDay(6),
            ),

            // ── derivatives-book portfolio: 5 positions + 1 sell ──
            AuditEvent(
                tradeId = "seed-db-spx-call-001",
                portfolioId = "derivatives-book",
                instrumentId = "SPX-CALL-5000",
                assetClass = "DERIVATIVE",
                side = "BUY",
                quantity = "100",
                priceAmount = "41.50",
                priceCurrency = "USD",
                tradedAt = dayStr(1),
                receivedAt = receivedAtDay(1),
            ),
            AuditEvent(
                tradeId = "seed-db-vix-put-001",
                portfolioId = "derivatives-book",
                instrumentId = "VIX-PUT-15",
                assetClass = "DERIVATIVE",
                side = "BUY",
                quantity = "200",
                priceAmount = "3.75",
                priceCurrency = "USD",
                tradedAt = dayStr(1),
                receivedAt = receivedAtDay(1),
            ),
            AuditEvent(
                tradeId = "seed-db-spx-put-001",
                portfolioId = "derivatives-book",
                instrumentId = "SPX-PUT-4500",
                assetClass = "DERIVATIVE",
                side = "BUY",
                quantity = "75",
                priceAmount = "33.00",
                priceCurrency = "USD",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
            ),
            AuditEvent(
                tradeId = "seed-db-nvda-001",
                portfolioId = "derivatives-book",
                instrumentId = "NVDA",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "50",
                priceAmount = "888.00",
                priceCurrency = "USD",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
            ),
            AuditEvent(
                tradeId = "seed-db-tsla-001",
                portfolioId = "derivatives-book",
                instrumentId = "TSLA",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "80",
                priceAmount = "249.50",
                priceCurrency = "USD",
                tradedAt = dayStr(4),
                receivedAt = receivedAtDay(4),
            ),
            AuditEvent(
                tradeId = "seed-db-spx-call-002",
                portfolioId = "derivatives-book",
                instrumentId = "SPX-CALL-5000",
                assetClass = "DERIVATIVE",
                side = "SELL",
                quantity = "40",
                priceAmount = "44.20",
                priceCurrency = "USD",
                tradedAt = dayStr(6),
                receivedAt = receivedAtDay(6),
            ),
        )
    }
}
