package com.kinetix.audit.seed

import com.kinetix.audit.model.AuditEvent
import com.kinetix.audit.persistence.AuditEventRepository
import org.slf4j.LoggerFactory
import java.time.Instant
import java.time.temporal.ChronoUnit

class DevDataSeeder(
    private val repository: AuditEventRepository,
) {
    private val log = LoggerFactory.getLogger(DevDataSeeder::class.java)

    suspend fun seed() {
        val anchor = repository.findByTradeId("seed-eq-aapl-001")
        if (anchor != null) {
            log.info("Audit seed anchor present, skipping seed")
            return
        }

        log.info("Seeding {} audit events", EVENTS.size)

        for (event in EVENTS) {
            repository.save(event)
        }

        log.info("Audit event seeding complete")
    }

    companion object {
        private val BASE_TIME = Instant.parse("2026-02-21T14:00:00Z")
        private fun day(n: Long): Instant = BASE_TIME.plus(n, ChronoUnit.DAYS)
        private fun receivedAfter(tradedAt: Instant): Instant = tradedAt.plusSeconds(1)

        private val RECEIVED_AT = receivedAfter(BASE_TIME)
        private const val TRADED_AT = "2026-02-21T14:00:00Z"

        private fun dayStr(n: Long): String = day(n).toString()
        private fun receivedAtDay(n: Long): Instant = receivedAfter(day(n))

        // Demo persona identities for realistic audit trail
        private const val TRADER_ID = "trader1"
        private const val TRADER_ROLE = "TRADER"
        private const val RISK_MGR_ID = "risk_mgr"
        private const val RISK_MGR_ROLE = "RISK_MANAGER"

        val EVENTS: List<AuditEvent> = listOf(
            // ── equity-growth portfolio: 5 equity trades ──
            AuditEvent(
                tradeId = "seed-eq-aapl-001",
                bookId ="equity-growth",
                instrumentId = "AAPL",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "25000",
                priceAmount = "185.50",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-eq-googl-001",
                bookId ="equity-growth",
                instrumentId = "GOOGL",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "15000",
                priceAmount = "175.20",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-eq-msft-001",
                bookId ="equity-growth",
                instrumentId = "MSFT",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "8000",
                priceAmount = "420.00",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-eq-amzn-001",
                bookId ="equity-growth",
                instrumentId = "AMZN",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "12000",
                priceAmount = "205.75",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-eq-tsla-001",
                bookId ="equity-growth",
                instrumentId = "TSLA",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "10000",
                priceAmount = "248.30",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),

            // ── multi-asset portfolio: 6 trades across asset classes ──
            AuditEvent(
                tradeId = "seed-ma-aapl-001",
                bookId ="multi-asset",
                instrumentId = "AAPL",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "5000",
                priceAmount = "186.00",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-ma-eurusd-001",
                bookId ="multi-asset",
                instrumentId = "EURUSD",
                assetClass = "FX",
                side = "BUY",
                quantity = "10000000",
                priceAmount = "1.0842",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-ma-us10y-001",
                bookId ="multi-asset",
                instrumentId = "US10Y",
                assetClass = "FIXED_INCOME",
                side = "BUY",
                quantity = "50000",
                priceAmount = "96.75",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-ma-gc-001",
                bookId ="multi-asset",
                instrumentId = "GC",
                assetClass = "COMMODITY",
                side = "BUY",
                quantity = "100",
                priceAmount = "2045.60",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-ma-spx-put-001",
                bookId ="multi-asset",
                instrumentId = "SPX-PUT-4500",
                assetClass = "DERIVATIVE",
                side = "BUY",
                quantity = "500",
                priceAmount = "32.50",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-ma-msft-001",
                bookId ="multi-asset",
                instrumentId = "MSFT",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "7500",
                priceAmount = "418.50",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),

            // ── fixed-income portfolio: 3 fixed income trades ──
            AuditEvent(
                tradeId = "seed-fi-us2y-001",
                bookId ="fixed-income",
                instrumentId = "US2Y",
                assetClass = "FIXED_INCOME",
                side = "BUY",
                quantity = "100000",
                priceAmount = "99.25",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-fi-us10y-001",
                bookId ="fixed-income",
                instrumentId = "US10Y",
                assetClass = "FIXED_INCOME",
                side = "BUY",
                quantity = "80000",
                priceAmount = "96.50",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-fi-us30y-001",
                bookId ="fixed-income",
                instrumentId = "US30Y",
                assetClass = "FIXED_INCOME",
                side = "BUY",
                quantity = "50000",
                priceAmount = "92.10",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),

            // ── emerging-markets portfolio: 5 positions + 1 sell ──
            AuditEvent(
                tradeId = "seed-em-baba-001",
                bookId ="emerging-markets",
                instrumentId = "BABA",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "40000",
                priceAmount = "83.20",
                priceCurrency = "USD",
                tradedAt = dayStr(1),
                receivedAt = receivedAtDay(1),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-em-tsla-001",
                bookId ="emerging-markets",
                instrumentId = "TSLA",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "6000",
                priceAmount = "250.10",
                priceCurrency = "USD",
                tradedAt = dayStr(1),
                receivedAt = receivedAtDay(1),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-em-eurusd-001",
                bookId ="emerging-markets",
                instrumentId = "EURUSD",
                assetClass = "FX",
                side = "BUY",
                quantity = "8000000",
                priceAmount = "1.0850",
                priceCurrency = "USD",
                tradedAt = dayStr(1),
                receivedAt = receivedAtDay(1),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-em-gbpusd-001",
                bookId ="emerging-markets",
                instrumentId = "GBPUSD",
                assetClass = "FX",
                side = "BUY",
                quantity = "5000000",
                priceAmount = "1.2580",
                priceCurrency = "USD",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-em-usdjpy-001",
                bookId ="emerging-markets",
                instrumentId = "USDJPY",
                assetClass = "FX",
                side = "BUY",
                quantity = "10000000",
                priceAmount = "150.20",
                priceCurrency = "USD",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-em-baba-002",
                bookId ="emerging-markets",
                instrumentId = "BABA",
                assetClass = "EQUITY",
                side = "SELL",
                quantity = "10000",
                priceAmount = "86.50",
                priceCurrency = "USD",
                tradedAt = dayStr(4),
                receivedAt = receivedAtDay(4),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),

            // ── macro-hedge portfolio: 6 positions + 1 sell ──
            AuditEvent(
                tradeId = "seed-mh-usdjpy-001",
                bookId ="macro-hedge",
                instrumentId = "USDJPY",
                assetClass = "FX",
                side = "BUY",
                quantity = "15000000",
                priceAmount = "149.80",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
                userId = RISK_MGR_ID,
                userRole = RISK_MGR_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-mh-gc-001",
                bookId ="macro-hedge",
                instrumentId = "GC",
                assetClass = "COMMODITY",
                side = "BUY",
                quantity = "200",
                priceAmount = "2040.00",
                priceCurrency = "USD",
                tradedAt = TRADED_AT,
                receivedAt = RECEIVED_AT,
                userId = RISK_MGR_ID,
                userRole = RISK_MGR_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-mh-cl-001",
                bookId ="macro-hedge",
                instrumentId = "CL",
                assetClass = "COMMODITY",
                side = "BUY",
                quantity = "500",
                priceAmount = "76.80",
                priceCurrency = "USD",
                tradedAt = dayStr(1),
                receivedAt = receivedAtDay(1),
                userId = RISK_MGR_ID,
                userRole = RISK_MGR_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-mh-si-001",
                bookId ="macro-hedge",
                instrumentId = "SI",
                assetClass = "COMMODITY",
                side = "BUY",
                quantity = "200",
                priceAmount = "23.10",
                priceCurrency = "USD",
                tradedAt = dayStr(1),
                receivedAt = receivedAtDay(1),
                userId = RISK_MGR_ID,
                userRole = RISK_MGR_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-mh-de10y-001",
                bookId ="macro-hedge",
                instrumentId = "DE10Y",
                assetClass = "FIXED_INCOME",
                side = "BUY",
                quantity = "30000",
                priceAmount = "97.80",
                priceCurrency = "EUR",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
                userId = RISK_MGR_ID,
                userRole = RISK_MGR_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-mh-spx-put-001",
                bookId ="macro-hedge",
                instrumentId = "SPX-PUT-4500",
                assetClass = "DERIVATIVE",
                side = "BUY",
                quantity = "800",
                priceAmount = "31.20",
                priceCurrency = "USD",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
                userId = RISK_MGR_ID,
                userRole = RISK_MGR_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-mh-gc-002",
                bookId ="macro-hedge",
                instrumentId = "GC",
                assetClass = "COMMODITY",
                side = "SELL",
                quantity = "50",
                priceAmount = "2060.50",
                priceCurrency = "USD",
                tradedAt = dayStr(4),
                receivedAt = receivedAtDay(4),
                userId = RISK_MGR_ID,
                userRole = RISK_MGR_ROLE,
            ),

            // ── tech-momentum portfolio: 4 positions + 1 sell ──
            AuditEvent(
                tradeId = "seed-tm-nvda-001",
                bookId ="tech-momentum",
                instrumentId = "NVDA",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "5000",
                priceAmount = "885.00",
                priceCurrency = "USD",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-tm-meta-001",
                bookId ="tech-momentum",
                instrumentId = "META",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "8000",
                priceAmount = "502.30",
                priceCurrency = "USD",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-tm-msft-001",
                bookId ="tech-momentum",
                instrumentId = "MSFT",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "6000",
                priceAmount = "421.50",
                priceCurrency = "USD",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-tm-googl-001",
                bookId ="tech-momentum",
                instrumentId = "GOOGL",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "12000",
                priceAmount = "176.80",
                priceCurrency = "USD",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-tm-meta-002",
                bookId ="tech-momentum",
                instrumentId = "META",
                assetClass = "EQUITY",
                side = "SELL",
                quantity = "2000",
                priceAmount = "510.00",
                priceCurrency = "USD",
                tradedAt = dayStr(6),
                receivedAt = receivedAtDay(6),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),

            // ── balanced-income portfolio: 5 positions + 1 sell ──
            AuditEvent(
                tradeId = "seed-bi-us10y-001",
                bookId ="balanced-income",
                instrumentId = "US10Y",
                assetClass = "FIXED_INCOME",
                side = "BUY",
                quantity = "60000",
                priceAmount = "96.60",
                priceCurrency = "USD",
                tradedAt = dayStr(1),
                receivedAt = receivedAtDay(1),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-bi-us30y-001",
                bookId ="balanced-income",
                instrumentId = "US30Y",
                assetClass = "FIXED_INCOME",
                side = "BUY",
                quantity = "40000",
                priceAmount = "92.30",
                priceCurrency = "USD",
                tradedAt = dayStr(1),
                receivedAt = receivedAtDay(1),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-bi-de10y-001",
                bookId ="balanced-income",
                instrumentId = "DE10Y",
                assetClass = "FIXED_INCOME",
                side = "BUY",
                quantity = "25000",
                priceAmount = "97.90",
                priceCurrency = "EUR",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-bi-jpm-001",
                bookId ="balanced-income",
                instrumentId = "JPM",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "15000",
                priceAmount = "208.40",
                priceCurrency = "USD",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-bi-aapl-001",
                bookId ="balanced-income",
                instrumentId = "AAPL",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "7000",
                priceAmount = "187.20",
                priceCurrency = "USD",
                tradedAt = dayStr(4),
                receivedAt = receivedAtDay(4),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-bi-us30y-002",
                bookId ="balanced-income",
                instrumentId = "US30Y",
                assetClass = "FIXED_INCOME",
                side = "SELL",
                quantity = "10000",
                priceAmount = "93.10",
                priceCurrency = "USD",
                tradedAt = dayStr(6),
                receivedAt = receivedAtDay(6),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),

            // ── derivatives-book portfolio: 5 positions + 1 sell ──
            AuditEvent(
                tradeId = "seed-db-spx-call-001",
                bookId ="derivatives-book",
                instrumentId = "SPX-CALL-5000",
                assetClass = "DERIVATIVE",
                side = "BUY",
                quantity = "2000",
                priceAmount = "41.50",
                priceCurrency = "USD",
                tradedAt = dayStr(1),
                receivedAt = receivedAtDay(1),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-db-vix-put-001",
                bookId ="derivatives-book",
                instrumentId = "VIX-PUT-15",
                assetClass = "DERIVATIVE",
                side = "BUY",
                quantity = "5000",
                priceAmount = "3.75",
                priceCurrency = "USD",
                tradedAt = dayStr(1),
                receivedAt = receivedAtDay(1),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-db-spx-put-001",
                bookId ="derivatives-book",
                instrumentId = "SPX-PUT-4500",
                assetClass = "DERIVATIVE",
                side = "BUY",
                quantity = "1500",
                priceAmount = "33.00",
                priceCurrency = "USD",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-db-nvda-001",
                bookId ="derivatives-book",
                instrumentId = "NVDA",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "5000",
                priceAmount = "888.00",
                priceCurrency = "USD",
                tradedAt = dayStr(2),
                receivedAt = receivedAtDay(2),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-db-tsla-001",
                bookId ="derivatives-book",
                instrumentId = "TSLA",
                assetClass = "EQUITY",
                side = "BUY",
                quantity = "8000",
                priceAmount = "249.50",
                priceCurrency = "USD",
                tradedAt = dayStr(4),
                receivedAt = receivedAtDay(4),
                userId = TRADER_ID,
                userRole = TRADER_ROLE,
            ),
            AuditEvent(
                tradeId = "seed-db-spx-call-002",
                bookId ="derivatives-book",
                instrumentId = "SPX-CALL-5000",
                assetClass = "DERIVATIVE",
                side = "SELL",
                quantity = "800",
                priceAmount = "44.20",
                priceCurrency = "USD",
                tradedAt = dayStr(6),
                receivedAt = receivedAtDay(6),
                userId = RISK_MGR_ID,
                userRole = RISK_MGR_ROLE,
            ),
        )
    }
}
