package com.kinetix.common.audit

enum class AuditEventType {
    TRADE_BOOKED,
    TRADE_AMENDED,
    TRADE_CANCELLED,
    RISK_CALCULATION_COMPLETED,
    STRESS_TEST_RUN,
    MODEL_STATUS_CHANGED,
    LIMIT_BREACHED,
    LIMIT_INCREASE_APPROVED,
    SCENARIO_APPROVED,
    SCENARIO_RETIRED,
    EOD_PROMOTED,
    SUBMISSION_APPROVED,
    RBAC_ACCESS_DENIED,
    REPORT_GENERATED,
}
