# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kinetix/common/types.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kinetix/common/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1akinetix/common/types.proto\x12\x0ekinetix.common\x1a\x1fgoogle/protobuf/timestamp.proto\")\n\x05Money\x12\x0e\n\x06\x61mount\x18\x01 \x01(\t\x12\x10\n\x08\x63urrency\x18\x02 \x01(\t\"\x1c\n\x0bPortfolioId\x12\r\n\x05value\x18\x01 \x01(\t\"\x18\n\x07TradeId\x12\r\n\x05value\x18\x01 \x01(\t\"\x1d\n\x0cInstrumentId\x12\r\n\x05value\x18\x01 \x01(\t\"\xbc\x02\n\x08Position\x12\x31\n\x0cportfolio_id\x18\x01 \x01(\x0b\x32\x1b.kinetix.common.PortfolioId\x12\x33\n\rinstrument_id\x18\x02 \x01(\x0b\x32\x1c.kinetix.common.InstrumentId\x12/\n\x0b\x61sset_class\x18\x03 \x01(\x0e\x32\x1a.kinetix.common.AssetClass\x12\x10\n\x08quantity\x18\x04 \x01(\x01\x12+\n\x0cmarket_value\x18\x05 \x01(\x0b\x32\x15.kinetix.common.Money\x12-\n\x0eunrealized_pnl\x18\x06 \x01(\x0b\x32\x15.kinetix.common.Money\x12)\n\x05\x61s_of\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*n\n\nAssetClass\x12\x1b\n\x17\x41SSET_CLASS_UNSPECIFIED\x10\x00\x12\n\n\x06\x45QUITY\x10\x01\x12\x10\n\x0c\x46IXED_INCOME\x10\x02\x12\x06\n\x02\x46X\x10\x03\x12\r\n\tCOMMODITY\x10\x04\x12\x0e\n\nDERIVATIVE\x10\x05\x42\x1c\n\x18\x63om.kinetix.proto.commonP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kinetix.common.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.kinetix.proto.commonP\001'
  _globals['_ASSETCLASS']._serialized_start=528
  _globals['_ASSETCLASS']._serialized_end=638
  _globals['_MONEY']._serialized_start=79
  _globals['_MONEY']._serialized_end=120
  _globals['_PORTFOLIOID']._serialized_start=122
  _globals['_PORTFOLIOID']._serialized_end=150
  _globals['_TRADEID']._serialized_start=152
  _globals['_TRADEID']._serialized_end=176
  _globals['_INSTRUMENTID']._serialized_start=178
  _globals['_INSTRUMENTID']._serialized_end=207
  _globals['_POSITION']._serialized_start=210
  _globals['_POSITION']._serialized_end=526
# @@protoc_insertion_point(module_scope)
