# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kinetix.risk import market_data_dependencies_pb2 as kinetix_dot_risk_dot_market__data__dependencies__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kinetix/risk/market_data_dependencies_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketDataDependenciesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DiscoverDependencies = channel.unary_unary(
                '/kinetix.risk.MarketDataDependenciesService/DiscoverDependencies',
                request_serializer=kinetix_dot_risk_dot_market__data__dependencies__pb2.DataDependenciesRequest.SerializeToString,
                response_deserializer=kinetix_dot_risk_dot_market__data__dependencies__pb2.DataDependenciesResponse.FromString,
                _registered_method=True)


class MarketDataDependenciesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DiscoverDependencies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketDataDependenciesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DiscoverDependencies': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverDependencies,
                    request_deserializer=kinetix_dot_risk_dot_market__data__dependencies__pb2.DataDependenciesRequest.FromString,
                    response_serializer=kinetix_dot_risk_dot_market__data__dependencies__pb2.DataDependenciesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kinetix.risk.MarketDataDependenciesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kinetix.risk.MarketDataDependenciesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketDataDependenciesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DiscoverDependencies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kinetix.risk.MarketDataDependenciesService/DiscoverDependencies',
            kinetix_dot_risk_dot_market__data__dependencies__pb2.DataDependenciesRequest.SerializeToString,
            kinetix_dot_risk_dot_market__data__dependencies__pb2.DataDependenciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
