# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kinetix/risk/market_data_dependencies.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kinetix/risk/market_data_dependencies.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kinetix.common import types_pb2 as kinetix_dot_common_dot_types__pb2
from kinetix.risk import risk_calculation_pb2 as kinetix_dot_risk_dot_risk__calculation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+kinetix/risk/market_data_dependencies.proto\x12\x0ckinetix.risk\x1a\x1akinetix/common/types.proto\x1a#kinetix/risk/risk_calculation.proto\"\x95\x02\n\x14MarketDataDependency\x12/\n\tdata_type\x18\x01 \x01(\x0e\x32\x1c.kinetix.risk.MarketDataType\x12\x15\n\rinstrument_id\x18\x02 \x01(\t\x12\x13\n\x0b\x61sset_class\x18\x03 \x01(\t\x12\x10\n\x08required\x18\x04 \x01(\x08\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x46\n\nparameters\x18\x06 \x03(\x0b\x32\x32.kinetix.risk.MarketDataDependency.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xbc\x01\n\x17\x44\x61taDependenciesRequest\x12+\n\tpositions\x18\x01 \x03(\x0b\x32\x18.kinetix.common.Position\x12;\n\x10\x63\x61lculation_type\x18\x02 \x01(\x0e\x32!.kinetix.risk.RiskCalculationType\x12\x37\n\x10\x63onfidence_level\x18\x03 \x01(\x0e\x32\x1d.kinetix.risk.ConfidenceLevel\"T\n\x18\x44\x61taDependenciesResponse\x12\x38\n\x0c\x64\x65pendencies\x18\x01 \x03(\x0b\x32\".kinetix.risk.MarketDataDependency*\xe8\x01\n\x0eMarketDataType\x12 \n\x1cMARKET_DATA_TYPE_UNSPECIFIED\x10\x00\x12\x0e\n\nSPOT_PRICE\x10\x01\x12\x15\n\x11HISTORICAL_PRICES\x10\x02\x12\x16\n\x12VOLATILITY_SURFACE\x10\x03\x12\x0f\n\x0bYIELD_CURVE\x10\x04\x12\x12\n\x0eRISK_FREE_RATE\x10\x05\x12\x12\n\x0e\x44IVIDEND_YIELD\x10\x06\x12\x11\n\rCREDIT_SPREAD\x10\x07\x12\x11\n\rFORWARD_CURVE\x10\x08\x12\x16\n\x12\x43ORRELATION_MATRIX\x10\t2\x86\x01\n\x1dMarketDataDependenciesService\x12\x65\n\x14\x44iscoverDependencies\x12%.kinetix.risk.DataDependenciesRequest\x1a&.kinetix.risk.DataDependenciesResponseB\x1a\n\x16\x63om.kinetix.proto.riskP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kinetix.risk.market_data_dependencies_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.kinetix.proto.riskP\001'
  _globals['_MARKETDATADEPENDENCY_PARAMETERSENTRY']._loaded_options = None
  _globals['_MARKETDATADEPENDENCY_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_MARKETDATATYPE']._serialized_start=684
  _globals['_MARKETDATATYPE']._serialized_end=916
  _globals['_MARKETDATADEPENDENCY']._serialized_start=127
  _globals['_MARKETDATADEPENDENCY']._serialized_end=404
  _globals['_MARKETDATADEPENDENCY_PARAMETERSENTRY']._serialized_start=355
  _globals['_MARKETDATADEPENDENCY_PARAMETERSENTRY']._serialized_end=404
  _globals['_DATADEPENDENCIESREQUEST']._serialized_start=407
  _globals['_DATADEPENDENCIESREQUEST']._serialized_end=595
  _globals['_DATADEPENDENCIESRESPONSE']._serialized_start=597
  _globals['_DATADEPENDENCIESRESPONSE']._serialized_end=681
  _globals['_MARKETDATADEPENDENCIESSERVICE']._serialized_start=919
  _globals['_MARKETDATADEPENDENCIESSERVICE']._serialized_end=1053
# @@protoc_insertion_point(module_scope)
