# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kinetix.risk import regulatory_reporting_pb2 as kinetix_dot_risk_dot_regulatory__reporting__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kinetix/risk/regulatory_reporting_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegulatoryReportingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateFrtb = channel.unary_unary(
                '/kinetix.risk.RegulatoryReportingService/CalculateFrtb',
                request_serializer=kinetix_dot_risk_dot_regulatory__reporting__pb2.FrtbRequest.SerializeToString,
                response_deserializer=kinetix_dot_risk_dot_regulatory__reporting__pb2.FrtbResponse.FromString,
                _registered_method=True)
        self.GenerateReport = channel.unary_unary(
                '/kinetix.risk.RegulatoryReportingService/GenerateReport',
                request_serializer=kinetix_dot_risk_dot_regulatory__reporting__pb2.GenerateReportRequest.SerializeToString,
                response_deserializer=kinetix_dot_risk_dot_regulatory__reporting__pb2.GenerateReportResponse.FromString,
                _registered_method=True)


class RegulatoryReportingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateFrtb(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegulatoryReportingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateFrtb': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateFrtb,
                    request_deserializer=kinetix_dot_risk_dot_regulatory__reporting__pb2.FrtbRequest.FromString,
                    response_serializer=kinetix_dot_risk_dot_regulatory__reporting__pb2.FrtbResponse.SerializeToString,
            ),
            'GenerateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReport,
                    request_deserializer=kinetix_dot_risk_dot_regulatory__reporting__pb2.GenerateReportRequest.FromString,
                    response_serializer=kinetix_dot_risk_dot_regulatory__reporting__pb2.GenerateReportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kinetix.risk.RegulatoryReportingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kinetix.risk.RegulatoryReportingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegulatoryReportingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateFrtb(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kinetix.risk.RegulatoryReportingService/CalculateFrtb',
            kinetix_dot_risk_dot_regulatory__reporting__pb2.FrtbRequest.SerializeToString,
            kinetix_dot_risk_dot_regulatory__reporting__pb2.FrtbResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kinetix.risk.RegulatoryReportingService/GenerateReport',
            kinetix_dot_risk_dot_regulatory__reporting__pb2.GenerateReportRequest.SerializeToString,
            kinetix_dot_risk_dot_regulatory__reporting__pb2.GenerateReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
