# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kinetix.risk import stress_testing_pb2 as kinetix_dot_risk_dot_stress__testing__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kinetix/risk/stress_testing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StressTestServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunStressTest = channel.unary_unary(
                '/kinetix.risk.StressTestService/RunStressTest',
                request_serializer=kinetix_dot_risk_dot_stress__testing__pb2.StressTestRequest.SerializeToString,
                response_deserializer=kinetix_dot_risk_dot_stress__testing__pb2.StressTestResponse.FromString,
                _registered_method=True)
        self.ListScenarios = channel.unary_unary(
                '/kinetix.risk.StressTestService/ListScenarios',
                request_serializer=kinetix_dot_risk_dot_stress__testing__pb2.ListScenariosRequest.SerializeToString,
                response_deserializer=kinetix_dot_risk_dot_stress__testing__pb2.ListScenariosResponse.FromString,
                _registered_method=True)
        self.CalculateGreeks = channel.unary_unary(
                '/kinetix.risk.StressTestService/CalculateGreeks',
                request_serializer=kinetix_dot_risk_dot_stress__testing__pb2.GreeksRequest.SerializeToString,
                response_deserializer=kinetix_dot_risk_dot_stress__testing__pb2.GreeksResponse.FromString,
                _registered_method=True)


class StressTestServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunStressTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListScenarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateGreeks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StressTestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunStressTest': grpc.unary_unary_rpc_method_handler(
                    servicer.RunStressTest,
                    request_deserializer=kinetix_dot_risk_dot_stress__testing__pb2.StressTestRequest.FromString,
                    response_serializer=kinetix_dot_risk_dot_stress__testing__pb2.StressTestResponse.SerializeToString,
            ),
            'ListScenarios': grpc.unary_unary_rpc_method_handler(
                    servicer.ListScenarios,
                    request_deserializer=kinetix_dot_risk_dot_stress__testing__pb2.ListScenariosRequest.FromString,
                    response_serializer=kinetix_dot_risk_dot_stress__testing__pb2.ListScenariosResponse.SerializeToString,
            ),
            'CalculateGreeks': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateGreeks,
                    request_deserializer=kinetix_dot_risk_dot_stress__testing__pb2.GreeksRequest.FromString,
                    response_serializer=kinetix_dot_risk_dot_stress__testing__pb2.GreeksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kinetix.risk.StressTestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kinetix.risk.StressTestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StressTestService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunStressTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kinetix.risk.StressTestService/RunStressTest',
            kinetix_dot_risk_dot_stress__testing__pb2.StressTestRequest.SerializeToString,
            kinetix_dot_risk_dot_stress__testing__pb2.StressTestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListScenarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kinetix.risk.StressTestService/ListScenarios',
            kinetix_dot_risk_dot_stress__testing__pb2.ListScenariosRequest.SerializeToString,
            kinetix_dot_risk_dot_stress__testing__pb2.ListScenariosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateGreeks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kinetix.risk.StressTestService/CalculateGreeks',
            kinetix_dot_risk_dot_stress__testing__pb2.GreeksRequest.SerializeToString,
            kinetix_dot_risk_dot_stress__testing__pb2.GreeksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
