ALTER TABLE trade_events ADD COLUMN instrument_type VARCHAR(50);
ALTER TABLE positions ADD COLUMN instrument_type VARCHAR(50);

-- Backfill from asset_class
UPDATE trade_events SET instrument_type = CASE asset_class
  WHEN 'EQUITY' THEN 'CASH_EQUITY'
  WHEN 'FIXED_INCOME' THEN 'GOVERNMENT_BOND'
  WHEN 'FX' THEN 'FX_SPOT'
  WHEN 'COMMODITY' THEN 'COMMODITY_FUTURE'
  WHEN 'DERIVATIVE' THEN 'CASH_EQUITY'
END;

UPDATE positions SET instrument_type = CASE asset_class
  WHEN 'EQUITY' THEN 'CASH_EQUITY'
  WHEN 'FIXED_INCOME' THEN 'GOVERNMENT_BOND'
  WHEN 'FX' THEN 'FX_SPOT'
  WHEN 'COMMODITY' THEN 'COMMODITY_FUTURE'
  WHEN 'DERIVATIVE' THEN 'CASH_EQUITY'
END;
